apiVersion: v1
kind: Service
metadata:
  name: skiffdb-headless
  labels:
    app.kubernetes.io/name: skiffdb
    app.kubernetes.io/part-of: skiffdb-benchmark
    app.kubernetes.io/managed-by: skiffdb-microk8s
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: skiffdb
    app.kubernetes.io/part-of: skiffdb-benchmark
  ports:
    - name: resp
      port: 6379
      targetPort: resp
    - name: admin
      port: 50051
      targetPort: admin
    - name: raft
      port: 7000
      targetPort: raft
